#!/bin/bash

########################################################################
# Load functions

if [ -f /usr/local/firewall/firewall.lib ] ; then
	. /usr/local/firewall/firewall.lib
else
	echo "ERROR: '/usr/local/firewall/firewall.lib' not found"
	exit 1
fi

########################################################################
# Main

case "${1}" in

	# Compile rules
	compile)
		compile_rules
	;;

	# Apply rules
	apply)
		apply_rules
	;;

	# Test rules
	try)
		stop_firewall
		# For nuts like me: schedule automatic deletion ...
		echo "/usr/local/sbin/firewall stop" |at now +2 minutes
		apply_rules
	;;

	# Update rules
	update)
		update_firewall
	;;

	# IPv4 and IPv6
	start)
		start_firewall
	;;
	stop)
		stop_firewall
	;;
	restart)
		stop_firewall
		start_firewall
	;;
	save)
		save_firewall
	;;

	# IPv4 only
	start-v4)
		start_V4_firewall
	;;
	stop-v4)
		stop_V4_firewall
	;;
	restart-v4)
		stop_V4_firewall
		start_V4_firewall
	;;
	save-v4)
		save_V4_firewall
	;;

	# IPv6 only
	start-v6)
		start_V6_firewall
	;;
	stop-v6)
		stop_V6_firewall
	;;
	restart-v6)
		stop_V6_firewall
		start_V6_firewall
	;;
	save-v6)
		save_V6_firewall
	;;

	# Help
	*)
cat<<EOT
Usage   : $0 <Command>

Commands: compile|try|apply|save|update|start|stop|restart

EOT
		exit 1
	;;

esac

exit ${rval}
